# Generated by Django 3.2.6 on 2021-08-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('B_ID', models.AutoField(primary_key=True, serialize=False)),
                ('B_Title', models.CharField(max_length=50, verbose_name='Blog Title')),
                ('B_Date', models.DateTimeField(auto_now=True, verbose_name='Blog Post Date')),
                ('B_Text', models.TextField(verbose_name='Blog Text')),
                ('B_Pics', models.TextField(verbose_name='Blog Media')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='UserHierarchy',
            fields=[
                ('UH_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UH_Name', models.CharField(max_length=20, verbose_name='Family Role')),
            ],
            options={
                'verbose_name': 'Hierarchy',
                'verbose_name_plural': 'Hierarchy',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('UL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UL_Login', models.CharField(max_length=20, unique=True, verbose_name='Login')),
                ('UL_Pass', models.CharField(max_length=20, verbose_name='Pass')),
                ('UL_Name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('UL_Email', models.CharField(max_length=50, verbose_name='eMail')),
                ('UL_Confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('UL_H', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userhierarchy', verbose_name='Family Role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='BlogLikes',
            fields=[
                ('BL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BL_Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.blog', verbose_name='Blog')),
                ('BL_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userlist', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blog Like',
                'verbose_name_plural': 'Blog Likes',
            },
        ),
        migrations.CreateModel(
            name='BlogCmt',
            fields=[
                ('BC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BC_Text', models.TextField(verbose_name='Blog Comment Text')),
                ('BC_Date', models.DateTimeField(auto_now=True)),
                ('BC_B_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.blog', verbose_name='Blog Comment')),
                ('BC_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userlist', verbose_name='Blog Commenter')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='B_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userlist', verbose_name='Blogger'),
        ),
        migrations.CreateModel(
            name='ArtList',
            fields=[
                ('AL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AL_Name', models.CharField(max_length=50, verbose_name='Art Name')),
                ('AL_AddDate', models.DateTimeField(auto_now=True, verbose_name='Date Add')),
                ('AL_ArtPath', models.TextField(verbose_name='Path to Art')),
                ('AL_Artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userlist', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Art',
                'verbose_name_plural': 'Arts',
            },
        ),
        migrations.CreateModel(
            name='ArtLikes',
            fields=[
                ('ALi_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ALi_Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.artlist', verbose_name='Art Name')),
                ('ALi_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userlist', verbose_name='Art Liker')),
            ],
            options={
                'verbose_name': 'Art Like',
                'verbose_name_plural': 'Art Likes',
            },
        ),
        migrations.CreateModel(
            name='ArtCmt',
            fields=[
                ('AC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AC_Text', models.TextField(verbose_name='Comment Text')),
                ('AC_Date', models.DateTimeField(auto_now=True, verbose_name='Comment Date')),
                ('AC_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='connector.userlist', verbose_name='Art Commenter')),
            ],
            options={
                'verbose_name': 'Art Comment',
                'verbose_name_plural': 'Art Comments',
            },
        ),
    ]
