# Generated by Django 3.2.6 on 2021-09-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='B_Pics',
            field=models.CharField(max_length=255, verbose_name='Blog Media'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='B_Text',
            field=models.CharField(max_length=500, verbose_name='Blog Text'),
        ),
    ]
