# Generated by Django 3.2.6 on 2021-09-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_rename_b_user_blog_b_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='B_User_id',
            new_name='B_User',
        ),
    ]
