# Generated by Django 3.2.6 on 2021-09-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_rename_b_user_id_blog_b_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='B_UserName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name'),
        ),
    ]
