# Generated by Django 3.2.6 on 2021-09-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_blog_b_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='B_User',
        ),
    ]
