# Generated by Django 3.2.6 on 2021-09-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_remove_blog_b_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcmt',
            name='AC_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.userlist', verbose_name='Art Commenter'),
        ),
        migrations.AlterField(
            model_name='artlikes',
            name='ALi_Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.artlist', verbose_name='Art Name'),
        ),
        migrations.AlterField(
            model_name='artlikes',
            name='ALi_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.userlist', verbose_name='Art Liker'),
        ),
        migrations.AlterField(
            model_name='artlist',
            name='AL_Artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.userlist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='blogcmt',
            name='BC_B_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.blog', verbose_name='Blog Comment'),
        ),
        migrations.AlterField(
            model_name='blogcmt',
            name='BC_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.userlist', verbose_name='Blog Commenter'),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='BL_Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='BL_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.userlist', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='UL_H',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.userhierarchy', verbose_name='Family Role'),
        ),
    ]
