# Generated by Django 3.2.6 on 2021-09-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_auto_20210905_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artcmt',
            name='AC_User',
        ),
        migrations.RemoveField(
            model_name='artlikes',
            name='ALi_Item',
        ),
        migrations.RemoveField(
            model_name='artlikes',
            name='ALi_User',
        ),
        migrations.RemoveField(
            model_name='artlist',
            name='AL_Artist',
        ),
        migrations.RemoveField(
            model_name='blogcmt',
            name='BC_B_ID',
        ),
        migrations.RemoveField(
            model_name='blogcmt',
            name='BC_User',
        ),
        migrations.RemoveField(
            model_name='bloglikes',
            name='BL_Item',
        ),
        migrations.RemoveField(
            model_name='bloglikes',
            name='BL_User',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='UL_H',
        ),
    ]
