# Generated by Django 3.2.6 on 2021-09-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20210905_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='B_Login',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Login'),
        ),
    ]
